spring:
  application:
    name: index-zuul-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
    api-b:
      path: /api-backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE
    api-c:
      path: /api-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW